import { Inter, Roboto_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Header from "../components/header";

const inter = Inter({ subsets: ["vietnamese"] });
const roboto_mono = Roboto_Mono({ subsets: ["vietnamese"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={String.prototype.concat(roboto_mono.className, " ")}>
        <Header />
        <div className="max-w-6xl mx-auto p-8">{children}</div>
      </body>
    </html>
  );
}
